### ISSUE TITLE
Disable multi dates 

### ISSUE THREAD

**Issue by mdfZEUNfps** [stephy/CalendarPicker#197]
Is possible that disable multi dates dynamically using disabledDates? Otherwise i want to disable specified days
![95310640_738939653307225_6071848253366730752_n](https://user-images.githubusercontent.com/16081365/81139174-67a63180-8f97-11ea-95c8-8cb7802d19c2.jpg)

**Comment by peacechen** [comment]
The `disabledDates` prop will automatically update the calendar if it changes.

**Comment by mdfZEUNfps** [comment]
> The `disabledDates` prop will automatically update the calendar if it changes.

Can you tell me more? I'm trying to coding like that. In item.tripDate has data like '2020-04-19', '2020-04-25', '2020-05-8', '2020-05-12', '2020-05-23', And they are not queued dates. So i wish to disable each one of them. How can it be done with 'disabledDates'?
`disabledDates={date => {
                            item.tripDate.map((item, index) => {
                                if (date.isBetween(item.start_date, item.end_date))
                                    return true;
                            })
                        }}`

**Comment by mdfZEUNfps** [comment]
> > The `disabledDates` prop will automatically update the calendar if it changes.
> 
> Can you tell me more? I'm trying to coding like that. In item.tripDate has data like '2020-04-19', '2020-04-25', '2020-05-8', '2020-05-12', '2020-05-23', And they are not queued dates. So i wish to disable each one of them. How can it be done with 'disabledDates'?
>
> 
> ```
 `disabledDates={date => {
>                         item.tripDate.map((item, index) => {
> 
>                             if (date.isBetween(item.start_date, item.end_date))
> 
>                                 return true;
> 
>                         })
> 
>                     }}`
> ```

**Comment by peacechen** [comment]
Try passing in an array.
```
  disabledDates={['2020-04-19', '2020-04-25', '2020-05-08', '2020-05-12', '2020-05-23']}
```

**Comment by mdfZEUNfps** [comment]
> Try passing in an array.
> 
> ```
>   disabledDates={['2020-04-19', '2020-04-25', '2020-05-08', '2020-05-12', '2020-05-23']}
> ```

I have tried it already. But no luck. When I tries this code it works without any problem. Does it even work by passing an array? Because I'm using the latest version of "react-native-calendar-picker".
`
disabledDates={date => {
    if (date.isBetween('2020-04-19', '2020-04-20')) {
        return true;
    }
    return false;
}}
`

**Comment by peacechen** [comment]
`disabledDates` supports an array, but there was a bug with the date comparison.  It's fixed on master but hasn't been published yet.  To try this in your project now, point the package.json directly to this repo.
```
dependencies: {
    "react-native-calendar-picker": "https://github.com/stephy/CalendarPicker",
}
```

**Comment by MannySAD** [comment]
@peacechen 
Ive been trying to pass a simple array this way: `disabledDates={['2020-06-06']}`

but no luck.

**Comment by peacechen** [comment]
Thanks @MannySAD for reporting the dependency error.  I pushed a commit that should fix this.

**Comment by mdfZEUNfps** [comment]
> `disabledDates` supports an array, but there was a bug with the date comparison. It's fixed on master but hasn't been published yet. To try this in your project now, point the package.json directly to this repo.
> 
> ```
> dependencies: {
>     "react-native-calendar-picker": "https://github.com/stephy/CalendarPicker",
> }
> ```
After I have changed from react-native-calendar-picker": "^6.0.6", to "react-native-calendar-picker": "https://github.com/stephy/CalendarPicker", disabledDates still doesn't have any effect. I guess this attribute need time to be fixed.

**Comment by peacechen** [comment]
You will need to run `npm install` again to pull the latest code.

If that still doesn't work, please run the example project in this repo.  I tested by adding the `disabledDates` prop and it disabled the correct dates.

**Comment by mdfZEUNfps** [comment]
> You will need to run `npm install` again to pull the latest code.
> 
> If that still doesn't work, please run the example project in this repo. I tested by adding the `disabledDates` prop and it disabled the correct dates.

Thanks. This one really helped me to figure out and everything works perfectly fine :D

**Comment by peacechen** [comment]
6.1.0 has been published
