### ISSUE TITLE
@providesModule naming collision

### ISSUE THREAD

**Issue by MyGuySi** [stephy/CalendarPicker#59]
I just upgraded to the latest RN and I'm getting a load of `@providesModule naming collision` errors coming from CalendarPicker - too many to paste them all but for example..

```
This warning is caused by a @providesModule declaration with the same name across two different files.
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/simon/dev/MyApp/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/simon/dev/MyApp/node_modules/react-native-calendar-picker/node_modules/react-native/local-cli/core/__fixtures__/files/package.json
```

I can't really figure out if this is a RN issue or something that can be addressed in this component. The latter seems more likely as it's the only package I've added since and comes up in all of the errors.

Thanks

RN v0.43.3
CalendarPicker v5.7.0

**Comment by MyGuySi** [comment]
So I've fixed this by pointing to the github repo rather than NPM. I'm guessing MASTER contains some fixes not yet published to NPM?

**Comment by ShadyXV** [comment]
I had the same problem after installing this package.
RN v0.43.3
CalendarPicker v5.7.0
Re-installing the package from did fix this issue.Thanks @MyGuySi

**Comment by LEEY19** [comment]
@MyGuySi hi, how did you 'point' to github repo?

**Comment by MyGuySi** [comment]
@LEEY19 here you go - http://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly

**Comment by blaine0611** [comment]
Thanks @MyGuySi , it helps me a lot

**Comment by chibeepatag** [comment]
After pointing to the github repo i got 
TransformError Couldn't find preset "babel-preset-expo"
Any hints?

**Comment by jjwon0** [comment]
This appears to have been fixed in c9bc2661775c6a39194275cdcec02d52acc1e352, which is why pointing at the GitHub repo should work.

@chibeepatag did it work after you removed and reinstalled the package?

**Comment by chibeepatag** [comment]
@jjwon0 nope. I checked the CalendarPicker's package.json and the changes of c9bc266 are there. But I'm still getting TransformError... Couldn't find preset "babel-preset-expo relative to directory "../node_modules/react-native-calendar-picker". Am I missing an installation?

**Comment by peacechen** [comment]
Dup of #55 and resolved in PR #56. 

babel-preset-expo was reported in #63 and resolved in PR #65.  Since it's a peer dependency, installing it to the parent project is the correct action.
